### PR TITLE
cip-19: Review status

### PR DESCRIPTION
**Pull request by Wondertan**
Change status to review

### CODE REVIEW

**Comment by Wondertan** [comment]
Or is it In Review? Also, where is the list of all the possible statuses?

**Comment by jcstein** [comment]
Review is correct, in CIP-1, https://github.com/celestiaorg/CIPs/blob/main/cips/cip-1.md#cip-process

**Comment by Wondertan** [comment]
Found it, CIP-1

**Comment by jcstein** [comment]
While CIP-1 doesn't mention anything about how long a CIP remains in Draft before going to Review, should this remain in Draft longer than just a few hours?

**Comment by Wondertan** [comment]
Actually, @jcstein, let's keep it as a draft; I will add one more container and ID type for the eds.

**Comment by rootulp** [comment]
> While CIP-1 doesn't mention anything about how long a CIP remains in Draft before going to Review, should this remain in Draft longer than just a few hours? cc @YazzyYaz @rootulp @ebuchman

IMO there doesn't need to be a minimum time enforced on how long a CIP is in Draft before moving to Review.

> Actually, @jcstein, let's keep it as a draft; I will add one more container and ID type for the eds.

Sounds good. Should this PR be closed?

**Comment by Wondertan** [comment]
We may, but the transition to review will happen anyway, and it's also the case that the change will be strictly additive and won't change the existing doc, so it still makes sense to keep what exist in the review stage

**Review by jcstein — APPROVED** [review]

**Pull request merged**
